export const FETCH_MODULEGROUPS_REQUEST = "FETCH_MODULEGROUPS_REQUEST";
export const FETCH_MODULEGROUPS_SUCCESS = "FETCH_MODULEGROUPS_SUCCESS";
export const FETCH_MODULEGROUPS_FAILURE = "FETCH_MODULEGROUPS_FAILURE";
