export const SAVE_USER = "SAVE_USER";
export const FETCH_PLAN_REQUEST = "FETCH_PLAN_REQUEST";
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS";
export const FETCH_PLAN_FAILURE = "FETCH_PLAN_FAILURE";
