export const FETCH_STUDYPROGRAMMES_REQUEST = "FETCH_STUDYPROGRAMMES_REQUEST";
export const FETCH_STUDYPROGRAMMES_SUCCESS = "FETCH_STUDYPROGRAMMES_SUCCESS";
export const FETCH_STUDYPROGRAMMES_FAILURE = "FETCH_STUDYPROGRAMMES_FAILURE";
